remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Services Docs | FrancoFantomius
description: This site is the documentation for the FrancoFantomius Services
show_downloads: false
